### ISSUE TITLE
Which addons are for Vanilla WoW (1.12)?

### ISSUE THREAD

**Issue by FrostShock** [Industrial/idAddon#1]
Hello,

I noticed you created a lot of WoW addons and I would like to ask you which ones are for Vanilla WoW (1.12) ?

Those who are not for 1.12 - are they all for Classic WoW (1.13)?

Thank you

**Comment by Industrial** [comment]
Hi!

Thanks for reaching out. This one is for 1.12: https://github.com/Industrial/idAddon/blob/master/idAddon.toc#L1

and this one is for live and 1.13: https://github.com/Industrial/idTweaks/blob/main/idTweaks.toc#L1

**Comment by FrostShock** [comment]
Thank you for the answer,
How about the other 15+ addons? 
https://github.com/Industrial/idQuestAutomation
https://github.com/Industrial/idWarlockDeleteShards
- are these two for 1.12 also?

**Comment by Industrial** [comment]
The rest are all ancient history and I can't give any guarantee about whether they will work or not. I keep them for archive purposes. If you look at the `.toc` file, the `Interface` line will tell you what version they were last used with.
